function speakText(text) {
  if (!window.speechSynthesis) {
    console.warn("Text-to-speech not supported.");
    return;
  }
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 0.8;  // Speed of speech
  utterance.pitch = 1; // Voice pitch
  utterance.lang = "en-US";
  window.speechSynthesis.cancel(); // Stop any ongoing speech
  window.speechSynthesis.speak(utterance);
}
function navigateTo(url) {
    document.body.classList.add("fade-out");
    setTimeout(() => {
      window.location.href = url;
    }, 500); // match the CSS transition duration
}
const text = "NavigateMR5 is a website built by UVA undergraduates to help making navigation at MR5 a lot easier!";
const speed = 100; // typing speed in milliseconds

let i = 0;
function typeWriter() {
  if (i < text.length) {
    document.getElementById("typewriter").textContent += text.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}

window.onload = typeWriter;

document.addEventListener("DOMContentLoaded", () => {
  const directions = document.getElementById("Directions");

  let startRoom = null;

  const roomNames = [
    "BME1st",
    "BMELarge",
    "SharedLab",
    "Kubelick",
    "Griffin",
    "French",
    "Sheybani",
    "Abebayehu",
    "Christ1",
    "Christ2",

    "BMESmall",
    "Atrium",
    "Papin",
    "Meyer",
    "SharedLabSpace",
    "Papin2",
    "Price1",
    "Price2",
    "Zunder",
    "Barker",
    "Peirce1",
    "Lazzara1",
    "Lazzara2",
    "Epstein",
    "Blemker",
    "Jane2",
    "Jane1",
    "Fallahi2",
    "Fallahi1",
    "Saucerman2",
    "Saucerman1",
    "Peirce2"
  ];

  const roomReadableNames = {
    BME1st: "BME 1st floor Foyer",
    BMELarge: "BME Large Classroom",
    SharedLab: "Shared Lab Space",
    Kubelick: "Kubelick Lab",
    Griffin: "Griffin Lab",
    French: "French Lab",
    Sheybani: "Sheybani Lab",
    Abebayehu: "Abebayehu Lab",
    Christ1: "Christ Lab #1",
    Christ2: "Christ Lab #2"
  };

  // Mock route instructions for demo — you can modify these
  const directionMap = {
    BME1st: {
      BMELarge: ["1. Walk straight through hallway until you reach hallway junction", "2. Turn left at hallway junction and destination is right in front of you"],
      SharedLab: ["1. Walk forward", "2. Turn right at hallway junction", "3. Destination is the third room to the left"],
      Kubelick: ["1. Walk forward", "2. Turn right at hallway junction", "3. Destination is the fourth room to the left"],
      Griffin: ["1.Walk forward", "2. Turn right at hallway junction", "3. Destination is the fifth room to the left"],
      French: ["1. Walk forward", "2. Turn right at hallway junction", "3. Destination is the seventh room to the left"],
      Sheybani: ["1. Walk forward", "2. Turn right at hallway junction", "3. Destination is the eighth room to the left"],
      Abebayehu: ["1. Walk forward", "2. Turn right at hallway junction", "3. Destination is the ninth room to the left"],
      Christ1: ["1. Walk forward", "2. Turn right at hallway junction", "3. Destination is the room before the last door on the left"],
      Christ2: ["1. Walk forward", "2. Turn right at hallway junction", "3. Room is last door on the left"],
    },
    BMELarge: {
      BME1st: ["1. Make your way into hallway", "2. Turn right", "3. Walk down hallway and your destination is at the end of the hallway"],
      SharedLab: ["1. Make your way into hallway", "2. Walk forward at the hallway junction", "3. Destination is the third room on the left"],
      Kubelick: ["1. Make your way into hallway", "2. Walk forward at the hallway junction", "3. Destination is fourth room on the left"],
      Griffin:["1. Make your way into hallway", "2. Walk forward at the hallway junction", "3. Destination is fifth room on the left"],
      French: ["1. Make your way into hallway", "2. Walk forward at the hallway junction", "3. Destination is seventh room on the left"],
      Sheybani: ["1. Make your way into hallway", "2. Walk forward at the hallway junction", "3. Destination is eighth room on the left"],
      Abebayehu:["1. Make your way into hallway", "2. Walk forward at the hallway junction", "3. Destination is ninth room on the left"],
      Christ1: ["1. Make way into hallway and walk straight down hallway", "2. Desination is the room right before last room at the end of the hallway, on your left"],
      Christ2:["1. Walk straight down hallway past the hallway junction", "2. Destination is last room on the left at the end of the hallway"],
    },
    
    SharedLab: {
      BME1st: ["1. Turn right and walk to hallway junction", "2. Turn left at hallway junction and walk down the hallway.", "3. Destination is at the end of the hall"],
      BMELarge: ["1. Turn right and walk all the way down past hallway junction and destination should be room right in front"],
      Kubelick: ["1. Turn left and walk down the hallway", "2. Destination is the next room on your left"],
      Griffin: ["1. Turn left and walk down the hallway", "2. Destination is the second room on your left"],
      French: ["1. Turn left and walk down the hallway", "2. Destination is the fourth room on your left"],
      Sheybani: ["1. Turn left and walk down the hallway", "2. Destination is the fifth room on your left"],
      Abebayehu: ["1. Turn left and walk down the hallway", "2. Destination is the sixth room on your left"],
      Christ1: ["1. Turn left and walk all the way down the hallway", "2. Destination is the room just before the last room on your left"],
      Christ2: ["1. Turn left and walk to the end of the hallway", "2. Destination is the last room on the left"]   
    },
    Kubelick: {
      BME1st: ["1. Turn right and walk down towards hallway junction", "2. Turn left at hallway junction", "3. Walk down the hall and your destination is in front of you"],
      BMELarge: ["1. Turn right and walk down towards hallway junction", "2. When you reach hallway junction, walk forward and your destination is in front of you"],
      SharedLab: ["1. Turn right and walk", "2. Destination is the first room to your right"],
      Griffin:["1. Turn left and walk", "2. Destination is the first room to your left"],
      French:["1. Turn left and walk", "2. Desintation is the third room to your left"],
      Sheybani: ["Turn left and walk", "2. Destination is the fourth room to your left"],
      Abebayehu:["Turn left and walk", "2. Destination is the fifth room to your left"],
      Christ1: ["Turn left and walk", "2. Destination is the room before the last room down the hall on your left"],
      Christ2: ["Turn left and walk", "2. Destination is the last room down the hall on your left"],
    },
    Griffin: {
      BME1st: ["1. Turn right and walk down towards hallway junction", "2. Turn left at hallway junction and your destination is down the hall and right in front of you"],
      BMELarge: ["1. Turn right and walk down towards hallway junction", "2. At hallway junction, walk forward past junction and destination is right in front of you"],
      SharedLab:["1. Turn right and walk down", "2. Destination is the second room on your right"],
      Kubelick: ["1. Turn right and walk down", "2. Destination is the first room on your right"],
      French:["1. Turn left and walk down", "2. Destination is the second room on your left"],
      Sheybani:["1. Turn left and walk down", "2. Destination is the third room on your left"],
      Abebayehu: ["1. Turn left and walk down", "2. Destination is the fourth room on your left"],
      Christ1: ["1. Turn left and walk down", "2. Destination is the room before the last room down the hall on your left"],
      Christ2: ["1. Turn left and walk down", "2. Destination is the last room down the hall on your left"],
    },
    French: {
      BME1st: ["1. Turn right and walk down towards hallway junction", "2. Turn left at hallway junction and your destination is down the hall and right in front of you"],
      BMELarge:["1. Turn right and walk down towards hallway junction", "2. At hallway junction, walk forward past junction and destination is right in front of you"],
      SharedLab: ["1. Turn right and walk down", "2. Destination is the fourth room on your right"],
      Kubelick: ["1. Turn right and walk down", "2. Destination is the third room on your right"],
      Griffin: ["1. Turn right and walk down", "2. Destination is the second room on your right"],
      Sheybani: ["1. Turn left and walk down", "2. Destination is the first room on your left"],
      Abebayehu: ["1. Turn left and walk down", "2. Destination is the second room on your left"],
      Christ1: ["1. Turn left and walk down", "2. Destination is the room before the last room down the hall on your left"],
      Christ2:["1. Turn left and walk down", "2. Destination is the last room down the hall on your left"],
    },
    Sheybani:{
      BME1st: ["1. Turn right and walk down towards hallway junction", "2. Turn left at hallway junction and your destination is down the hall and right in front of you"],
      BMELarge: ["1. Turn right and walk down towards hallway junction", "2. At hallway junction, walk forward past junction and destination is right in front of you"],
      SharedLab: ["1. Turn right and walk down", "2. Destination is the fifth room on your right"],
      Kubelick:["1. Turn right and walk down", "2. Destination is the fourth room on your right"],
      Griffin:["1. Turn right and walk down", "2. Destination is the third room on your right"],
      French:["1. Turn right and walk down", "2. Destination is the first room on your right"],
      Abebayehu:["1. Turn left and walk down", "2. Destination is the first room on your left"],
      Christ1: ["1. Turn left and walk down", "2. Destination is the second room on your left"],
      Christ2: ["1. Turn left and walk down the hallway and your destination is the last room down the hall"],
    },
    Abebayehu: {
      BME1st: ["1. Turn right and walk down towards hallway junction", "2. Turn left at hallway junction and your destination is down the hall and right in front of you"],
      BMELarge: ["1. Turn right and walk down towards hallway junction", "2. At hallway junction, walk forward past junction and destination is right in front of you"],
      SharedLab: ["1. Turn right and walk down", "2. Destination is the sixth room on your right"],
      Kubelick: ["1. Turn right and walk down", "2. Destination is the fifth room on your right"],
      Griffin: ["1. Turn right and walk down", "2. Destination is the fourth room on your right"],
      French: ["1. Turn right and walk down", "2. Destination is the second room on your right"],
      Sheybani: ["1. Turn right and walk down", "2. Destination is the first room on your right"],
      Christ1: ["1. Turn left and walk down", "2. Destination is the first room on your left"],
      Christ2:  ["1. Turn left and walk down", "2. Destination is the last room down the hall on your left"],
    },
    Christ1: {
      BME1st: ["1. Turn right and walk down towards hallway junction", "2. Turn left at hallway junction and your destination is down the hall and right in front of you"],
      BMELarge: ["1. Turn right and walk down towards hallway junction", "2. At hallway junction, walk forward past junction and destination is right in front of you"],
      SharedLab: ["1. Turn right and walk down", "2. Destination is the seventh room on your right"],
      Kubelick: ["1. Turn right and walk down", "2. Destination is the sixth room on your right"],
      Griffin: ["1. Turn right and walk down", "2. Destination is the fifth room on your right"],
      French: ["1. Turn right and walk down", "2. Destination is the third room on your right"],
      Sheybani: ["1. Turn right and walk down", "2. Destination is the second room on your right"],
      Abebayehu: ["1. Turn right and walk down", "2. Destination is the first room on your right"],
      Christ2: ["1. Turn left and walk down", "2. Destination is the first room to your left"],
    },
    Christ2: {
      BME1st: ["1. Turn right and walk down towards hallway junction", "2. Turn left at hallway junction and your destination is down the hall and right in front of you"],
      BMELarge: ["1. Turn right and walk down towards hallway junction", "2. At hallway junction, walk forward past junction and destination is right in front of you"],
      SharedLab: ["1. Turn right and walk down", "2. Destination is the eighth room on your right"],
      Kubelick:["1. Turn right and walk down", "2. Destination is the seventh room on your right"],
      Griffin:["1. Turn right and walk down", "2. Destination is the sixth room on your right"],
      French:["1. Turn right and walk down", "2. Destination is the fourth room on your right"],
      Sheybani:["1. Turn right and walk down", "2. Destination is the third room on your right"],
      Abebayehu:["1. Turn right and walk down", "2. Destination is the second room on your right"],
      Christ1:["1. Turn right and walk down", "2. Destination is the first room on your right"],
    },
    BMESmall: {
      Atrium: ["1. Walk forward and your destination should be up ahead."],
      Papin: ["1. Walk down the hallway until you reach hallway junction", "2. Turn left at hallway junction", "3. Destination is in front of you"],
      Meyer: ["1. Walk down the hallway until you reach hallway junction", "2. Turn left at hallway junction", "3. Walk forward into Papin Lab", "4. Turn right and destination is the room in front of you"],
      SharedLabSpace: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is first room on right"],
      Papin2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is second room on right"],
      Peirce2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is third room on the left"],
      Saucerman1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fourth room on left"],
      Saucerman2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fifth room on left"],
      Price1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is third room on right"],
      Price2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fourth room on right"],
      Zunder: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fifth room on right"],
      Barker: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is sixth room on right"],
      Peirce1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is seventh room on right"],
      Lazzara1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is eighth room on right"],
      Lazzara2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is ninth room on right"],
      Fallahi1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is sixth room on left"],
      Fallahi2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is seventh room on left"],
      Jane1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is eighth room on left"],
      Jane2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is ninth room on left"],
      Blemker: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is tenth room on left"],
      Epstein: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is eleventh room on left"]
    },
    Atrium: {
      BMESmall: ["1. Walk in direction opposite to hallway and destination should be in front of you"],
      Papin: ["1. Walk down the hallway until you reach hallway junction", "2. Turn left at hallway junction", "3. Destination is in front of you"],
      Meyer: ["1. Walk down the hallway until you reach hallway junction", "2. Turn left at hallway junction", "3. Walk forward into Papin Lab", "4. Turn right and destination is the room in front of you"],
      SharedLabSpace: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is first room on right"],
      Papin2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is second room on right"],
      Peirce2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is third room on the left"],
      Saucerman1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fourth room on left"],
      Saucerman2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fifth room on left"],
      Price1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is third room on right"],
      Price2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fourth room on right"],
      Zunder: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is fifth room on right"],
      Barker: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is sixth room on right"],
      Peirce1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is seventh room on right"],
      Lazzara1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is eighth room on right"],
      Lazzara2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is ninth room on right"],
      Fallahi1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is sixth room on left"],
      Fallahi2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is seventh room on left"],
      Jane1: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is eighth room on left"],
      Jane2: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is ninth room on left"],
      Blemker: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is tenth room on left"],
      Epstein: ["1. Walk down the hallway until you reach hallway junction", "2. Turn right at hallway junction", "3. Destination is eleventh room on left"]
    },
    SharedLabSpace:{
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Papin2: ["1. Turn right and destination is first room on your right"],
      Price1: ["1. Turn right and destination is second room on your right"],
      Price2: ["1. Turn right and destination is third room on your right"],
      Zunder: ["1. Turn right and destination is fourth room on your right"],
      Barker: ["1. Turn right and destination is fifth room on your right"],
      Peirce1: ["1. Turn right and destination is sixth room on your right"],
      Lazzara1: ["1. Turn right and destination is seventh room on your right"],
      Lazzara2: ["1. Turn right and destination is last room down the hall on your right"],
      Epstein: ["1. Turn right and destination is last room down the hall on your left"],
      Blemker: ["1. Turn right and destination is second to last room down the hall on your left"],
      Jane2: ["1. Turn right and walk down and count up to six doors on your right and your destination is the room opposite of the sixth door on your right."],
      Jane1: ["1. Turn right and walk down and count up to five doors on your right and your destination is the room opposite of the fifth door on your right."],
      Fallahi2: ["1. Turn right and walk down and count up to four doors on your right and your destination is the room opposite of the fourth door on your right."],
      Fallahi1: ["1. Turn right and walk down and count up to three doors on your right and your destination is the room opposite of the third door on your right."],
      Saucerman2: ["1. Turn right and walk down and count up to two doors on your right and your destination is the room opposite of the second door on your right."],
      Saucerman1: ["1. Turn right and your destination is the room opposite of the room to your right"],
      Peirce2: ["1. Destination is room right across from you."]
    },
    Papin2: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace: ["1. Turn left and destination is first room on left"],
      Price1: ["1. Turn right and destination is first room on your right"],
      Price2: ["1. Turn right and destination is second room on your right"],
      Zunder: ["1. Turn right and destination is third room on your right"],
      Barker: ["1. Turn right and destination is fourth room on your right"],
      Peirce1: ["1. Turn right and destination is fifth room on your right"],
      Lazzara1: ["1. Turn right and destination is sixth room on your right"],
      Lazzara2: ["1. Turn right and destination is last room down the hall on your right"],
      Epstein: ["1. Turn right and destination is last room down the hall on your left"],
      Blemker: ["1. Turn right and destination is second to last room down the hall on your left"],
      Jane2: ["1. Turn right and walk down and count up to five doors on your right and your destination is the room opposite of the fifth door on your right."],
      Jane1: ["1. Turn right and walk down and count up to four doors on your right and your destination is the room opposite of the fourth door on your right."],
      Fallahi2: ["1. Turn right and walk down and count up to three doors on your right and your destination is the room opposite of the third door on your right."],
      Fallahi1: ["1. Turn right and walk down and count up to two doors on your right and your destination is the room opposite of the second door on your right."],
      Saucerman2: ["1. Turn right and your destination is the room opposite of the room to your right"],
      Saucerman1: ["1. Your destination is room right across from you"],
      Peirce2: ["1. Destination is the room to the left of the room right across from you"],
    },
    Price1: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],  
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace: ["1. Turn left and destination is second room on left"],
      Papin2: ["1. Turn left and destination is the first room on left"],
      Price2: ["1. Turn right and destination is the first room on your right"],
      Zunder: ["1. Turn right and destination is second room on your right"],
      Barker: ["1. Turn right and destination is third room on your right"],
      Peirce1: ["1. Turn right and destination is fourth room on your right"],
      Lazzara1: ["1. Turn right and destination is second to last room on your right"],
      Lazzara2: ["1. Turn right and destination is last room down the hall on your right"],
      Epstein: ["1. Turn right and destination is last room down the hall on your left"],
      Blemker: ["1. Turn right and destination is second to last room down the hall on your left"],
      Jane2: ["1. Turn right and walk down and count up to four doors on your right and your destination is the room opposite of the fourth door on your right."],
      Jane1: ["1. Turn right and walk down and count up to three doors on your right and your destination is the room opposite of the third door on your right."],
      Fallahi2: ["1. Turn right and walk down and count up to two doors on your right and your destination is the room opposite of the second door on your right."],
      Fallahi1: ["1. Turn right and your destination is the room opposite of the room to your right"],
      Saucerman2: ["1. Destination is room across from you"],
      Saucerman1: ["1. Your destination is the room to the left of the room across from you"],
      Peirce2: ["1. Turn left and your destination is the second door on your right"],
    },
    Price2: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace: ["1. Turn left and your destination is third room on left"],
      Papin2: ["1. Turn left and your destination is second room on left"],
      Price1: ["Turn left and your destination is the room on your left"],
      Zunder: ["1. Turn right and destination is room on your right"],
      Barker: ["1. Turn right and destination is second room on your right"],
      Peirce1: ["1. Turn right and destination is third room on your right"],
      Lazzara1: ["1. Turn right and destination is second to last room on your right"],
      Lazzara2: ["1. Turn right and destination is last room down the hall on your right"],
      Epstein: ["1. Turn right and destination is last room down the hall on your left"],
      Blemker: ["1. Turn right and destination is second to last room down the hall on your left"],
      Jane2: ["1. Turn right and walk down and count up to three doors on your right and your destination is the room opposite of the third door on your right."],
      Jane1: ["1. Turn right and walk down and count up to two doors on your right and your destination is the room opposite of the second door on your right."],
      Fallahi2: ["1. Turn right and your destination is the room opposite of the room to your right"],
      Fallahi1: ["1. Destination is room across from you"],
      Saucerman2: ["1. Turn left and walk and destination is first room on right"],
      Saucerman1: ["1. Turn left and walk and destination is second room on right"],
      Peirce2: ["1. Turn left and walk and destination is third room on right"],
    },
    Zunder: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace: ["1. Turn left and destination is fourth room on left"],
      Papin2: ["1. Turn left and destination is third room on left"],
      Price1: ["1. Turn left and destination is second room on left"],
      Price2: ["1. Destination is room to your left"],
      Barker: ["1. Destination is room to your right"],
      Peirce1: ["1. Turn right and destination is second room on your right"],
      Lazzara1: ["1. Turn right and destination is third to last room on your right"],
      Lazzara2: ["1. Turn right and destination is last room down the hall on your right"],
      Epstein: ["1. Turn right and destination is last room down the hall on your left"],
      Blemker: ["1. Turn right and destination is second to last room down the hall on your left"],
      Jane2: ["1. Turn right and walk down and count up to two doors on your right and your destination is the room opposite of the second door on your right."],
      Jane1: ["1. Turn right and your destination is the room opposite of the room to your right"],
      Fallahi2: ["1. Destination is the room right across from you"],
      Fallahi1: ["1. Turn left and walk and destination is first room on right"],
      Saucerman2: ["1. Turn left and walk and destination is second room on right"],
      Saucerman1: ["1. Turn left and walk and destination is third room on right"],
      Peirce2: ["1. Turn left and walk and destination is fourth room on right"],
    },
    Barker: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace:["1. Turn left and your destination is fifth room on your left"],
      Papin2: ["1. Turn left and your destination is fourth room on your left"],
      Price1: ["1. Turn left and your destination is third room on your left"],
      Price2: ["1. Turn left and your destination is second room on your left"],
      Zunder: ["1. Destination is the room to your left"],
      Peirce1: ["1. Destination is the room to your right"],
      Lazzara1: ["1. Turn right and destination is second to last room on your right"],
      Lazzara2: ["1. Turn right and destination is last room down the hall on your right"],
      Epstein: ["1. Turn right and destination is last room down the hall on your left"],
      Blemker: ["1. Turn right and destination is second to last room down the hall on your left"],
      Jane2: ["1. Turn right and your destination is the room opposite to the room to your right"],
      Jane1: ["1. Destination is the room right across from you"],
      Fallahi2: ["1. Turn left and walk and destination is first room on right"],
      Fallahi1: ["1. Turn left and walk and destination is second room on right"],
      Saucerman2: ["1. Turn left and walk and destination is third room on right"],
      Saucerman1: ["1. Turn left and walk and destination is fourth room on right"],
      Peirce2: ["1. Turn left and walk and destination is fifth room on right"],
    },
    Peirce1: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace: ["1. Turn left and your destination is sixth room down the hall on your left"],
      Papin2: ["1. Turn left and your destination is fifth room down the hall on your left"],
      Price1: ["1. Turn left and your destination is fourth room down the hall on your left"],
      Price2: ["1. Turn left and your destination is third room down the hall on your left"],
      Zunder: ["1. Turn left and your destination is second room down the hall on your left"],
      Barker: ["1. Destination is room to your left"],
      Lazzara1: ["1. Turn right and destination is room to your right"],
      Lazzara2: ["1. Turn right and destination is last room down the hall on your right"],
      Epstein: ["1. Turn right and destination is last room down the hall on your left"],
      Blemker: ["1. Turn right and destination is second to last room down the hall on your left"],
      Jane2: ["1. Destination is room right across from you"],
      Jane1: ["1. Turn left and walk and destination is first room on right"],
      Fallahi2: ["1. Turn left and walk and destination is second room on right"],
      Fallahi1: ["1. Turn left and walk and destination is third room on right"],
      Saucerman2: ["1. Turn left and walk and destination is fourth room on right"],
      Saucerman1: ["1. Turn left and walk and destination is fifth room on right"],
      Peirce2: ["1. Turn left and walk and destination is sixth room on right"],
    },
    Lazzara1: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace: ["1. Turn left and your destination is seventh room on your left"],
      Papin2: ["1. Turn left and your destination is sixth room on your left"],
      Price1:["1. Turn left and your destination is fifth room on your left"],
      Price2:["1. Turn left and your destination is fourth room on your left"],
      Zunder: ["1. Turn left and your destination is third room on your left"],
      Barker:["1. Turn left and your destination is second room on your left"],
      Peirce1: ["1. Destination is room to your left"],
      Lazarra2: ["1. Destination is room to your right"],
      Epstein: ["1. Turn right and destination is last door down the hall to your left"],
      Blemker: ["1. Destination is room across from you"],
      Jane2: ["1. Turn left and walk and destination is first room on right"],
      Jane1: ["1. Turn left and walk and destination is second room on right"],
      Fallahi2: ["1. Turn left and walk and destination is third room on right"],
      Fallahi1: ["1. Turn left and walk and destination is fourth room on right"],
      Saucerman2: ["1. Turn left and walk and destination is fifth room on right"],
      Saucerman1: ["1. Turn left and walk and destination is sixth room on right"],
      Peirce2: ["1. Turn left and walk and destination is seventh room on right"],
    },
    Lazarra2: {
      Atrium: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall: ["1. Turn left and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      Meyer: ["1. Turn left and make your way into hallway junction", "Walk forward past junction and destination is in front of you"],
      SharedLabSpace: ["1. Turn left and your destination is eighth room on your left"],
      Papin2: ["1. Turn left and your destination is seventh room on your left"],
      Price1: ["1. Turn left and your destination is sixth room on your left"],
      Price2: ["1. Turn left and your destination is fifth room on your left"],
      Zunder: ["1. Turn left and your destination is fourth room on your left"],
      Barker: ["1. Turn left and your destination is third room on your left"],
      Peirce1: ["1. Turn left and your destination is second room on your left"],
      Lazzara1: ["1. Destination is room to your left"],
      Epstein: ["1. Destination is room right across from you"],
      Blemker: ["1. Turn left and walk and destination is first room on your right"],
      Jane2: ["1. Turn left and walk and destination is second room on your right"],
      Jane1: ["1. Turn left and walk and destination is third room on your right"],
      Fallahi2: ["1. Turn left and walk and destination is fourth room on your right"],
      Fallahi1: ["1. Turn left and walk and destination is fifth room on your right"],
      Saucerman2: ["1. Turn left and walk and destination is sixth room on your right"],
      Saucerman1: ["1. Turn left and walk and destination is seventh room on your right"],
      Peirce2: ["1. Turn left and walk and destination is eighth room on your right"],
    },
    Peirce2: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
	    Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
	    Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
	    SharedLabSpace: ["1. Walk forward, and your destination is in front of you"],
	    Papin2:["1. Walk forward, and your destination is the door to the left"],
	    Price1:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the right"],
	    Price2:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the right"],
	    Zunder:["1. Turn left, walk down the hallway.", "2. Your destination is the fifth door on the right"],
	    Barker:["1. Turn left, walk down the hallway.", "2. Your destination is the sixth door on the right"],
	    Peirce1:["1. Turn left, walk down the hallway.", "2. Your destination is the seventh door on the right"],
	    Lazzara1:["1. Turn left, walk down the hallway.", "2. Your destination is the eighth door on the right"],
	    Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
	    Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
	    Blemker:["1. Turn left, walk down the hallway.", "2. Your destination is the seventh door on the left"],
	    Jane2:["1. Turn left, walk down the hallway.", "2. Your destination is the sixth door on the left"],
	    Jane1:["1. Turn left, walk down the hallway.", "2. Your destination is the fifth door on the left"],
	    Fallahi2:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the left"],
	    Fallahi1:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the left"],
	    Saucerman2:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the left"],
	    Saucerman1:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the left"],
    },
    Saucerman1: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the first door to the left"],
      Papin2:["1. Walk forward, and your destination is in front of you"],
      Price1:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the right"],
      Price2:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the right"],
      Zunder:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the right"],
      Barker:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the right"],
      Peirce1:["1. Turn left, walk down the hallway.", "2. Your destination is the fifth door on the right"],
      Peirce2:["1. Turn left, walk down the hallway.", "2. Your destination is the sixth door on the left"],
      Lazzara1:["1. Turn left, walk down the hallway.", "2. Your destination is the seventh door on the right"],
      Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
      Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
      Blemker:["1. Turn left, walk down the hallway.", "2. Your destination is the sixth door on the left"],
      Jane2:["1. Turn left, walk down the hallway.", "2. Your destination is the fifth door on the left"],
      Jane1:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the left"],
      Fallahi2:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the left"],
      Fallahi1:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the left"],
      Saucerman2:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the left"],
    },
    Saucerman2: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the second door on the left"],
      Papin2:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Price1:["1. Walk forward, and your destination is in front of you"],
      Price2:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the right"],
      Zunder:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the right"],
      Barker:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the right"],
      Peirce1:["1. Turn left, walk down the hallway.", "2. Your destination is the fifth door on the right"],
      Peirce2:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the right"],
      Lazzara1:["1. Turn left, walk down the hallway.", "2. Your destination is the sixth door on the right"],
      Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
      Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
      Blemker:["1. Turn left, walk down the hallway.", "2. Your destination is the fifth door on the left"],
      Jane2:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the left"],
      Jane1:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the left"],
      Fallahi2:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the left"],
      Fallahi1:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the left"],
      Saucerman1:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the right"],
    },
    Fallahi1: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the third door on the left"],
      Papin2:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Price1:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Price2:["1. Walk forward, and your destination is in front of you"],
      Zunder:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the right"],
      Barker:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the right"],
      Peirce1:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the right"],
      Peirce2:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the right"],
      Lazzara1:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the right"],
      Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
      Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
      Blemker:["1. Turn left, walk down the hallway.", "2. Your destination is the fourth door on the left"],
      Jane2:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the left"],
      Jane1:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the left"],
      Fallahi2:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the left"],
      Saucerman2:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the right"],
      Saucerman1:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the right"],
    },
    Fallahi2: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the fourth door on the left"],
      Papin2:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the left"],
      Price1:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Price2:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Zunder:["1. Walk forward, and your destination is in front of you"],
      Barker:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the right"],
      Peirce1:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the right"],
      Peirce2:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the right"],
      Lazzara1:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the right"],
      Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
      Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
      Blemker:["1. Turn left, walk down the hallway.", "2. Your destination is the third door on the left"],
      Jane2:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the left"],
      Jane1:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the left"],
      Fallahi1:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the right"],
      Saucerman2:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the right"],
      Saucerman1:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the right"],
    },
    Jane1: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the fifth door on the left"],
      Papin2:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the left"],
      Price1:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the left"],
      Price2:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Zunder:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Barker:["1. Walk forward, and your destination is in front of you"],
      Peirce1:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the right"],
      Peirce2:["1. Turn right, walk down the hallway.", "2. Your destination is the fifth door on the right"],
      Lazzara1:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the right"],
      Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
      Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
      Blemker:["1. Turn left, walk down the hallway.", "2. Your destination is the second door on the left"],
      Jane2:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the left"],
      Fallahi2:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the right"],
      Fallahi1:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the right"],
      Saucerman2:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the right"],
      Saucerman1:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the right"],
    },
    Jane2: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the sixth door on the left"],
      Papin2:["1. Turn right, walk down the hallway.", "2. Your destination is the fifth door on the left"],
      Price1:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the left"],
      Price2:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the left"],
      Zunder:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Barker:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Peirce1:["1. Walk forward, and your destination is in front of you"],
      Peirce2:["1. Turn right, walk down the hallway.", "2. Your destination is the sixth door on the right"],
      Lazzara1:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the right"],
      Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
      Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
      Blemker:["1. Turn left, walk down the hallway.", "2. Your destination is the first door on the left"],
      Jane1:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Fallahi2:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the right"],
      Fallahi1:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the right"],
      Saucerman2:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the right"],
      Saucerman1:["1. Turn right, walk down the hallway.", "2. Your destination is the fifth door on the right"],
    },
    Blemker: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the seventh door on the left"],
      Papin2:["1. Turn right, walk down the hallway.", "2. Your destination is the sixth door on the left"],
      Price1:["1. Turn right, walk down the hallway.", "2. Your destination is the fifth door on the left"],
      Price2:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the left"],
      Zunder:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the left"],
      Barker:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Peirce1:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Peirce2:["1. Turn right, walk down the hallway.", "2. Your destination is the seventh door on the right"],
      Lazzara1:["1. Walk forward, and your destination is in front of you"],
      Lazzara2:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the right"],
      Epstein:["1. Turn left, walk down the hallway.", "2. Your destination is the last door on the left"],
      Jane2:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Jane1:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Fallahi2:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the right"],
      Fallahi1:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the right"],
      Saucerman2:["1. Turn right, walk down the hallway.", "2. Your destination is the fifth door on the right"],
      Saucerman1:["1. Turn right, walk down the hallway.", "2. Your destination is the sixth door on the right"],
    },
    Epstein: {
      Atrium: ["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      BMESmall:["1. Turn right and make your way into hallway junction.", "2. Turn left at hallway junction and walk down the hallway and destination is in front of you"],
      Papin:["1. Turn right and make your way into the hallway junction." , "Walk forward past junction and your destination is in front of you"],
      Meyer:["1. Turn right and make your way into the hallway junction.” , “Walk forward past junction and your destination is in front of you"],
      SharedLabSpace: ["1. Turn right and walk forward, and your destination is the eighth door on the left"],
      Papin2:["1. Turn right, walk down the hallway.", "2. Your destination is the seventh door on the left"],
      Price1:["1. Turn right, walk down the hallway.", "2. Your destination is the sixth door on the left"],
      Price2:["1. Turn right, walk down the hallway.", "2. Your destination is the fifth door on the left"],
      Zunder:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the left"],
      Barker:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the left"],
      Peirce1:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Peirce2:["1. Turn right, walk down the hallway.", "2. Your destination is the eighth door on the right"],
      Lazzara1:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the left"],
      Lazzara2:["1. Walk forward, and your destination is in front of you"],
      Blemker:["1. Turn right, walk down the hallway.", "2. Your destination is the first door on the right"],
      Jane2:["1. Turn right, walk down the hallway.", "2. Your destination is the second door on the left"],
      Jane1:["1. Turn right, walk down the hallway.", "2. Your destination is the third door on the left"],
      Fallahi2:["1. Turn right, walk down the hallway.", "2. Your destination is the fourth door on the right"],
      Fallahi1:["1. Turn right, walk down the hallway.", "2. Your destination is the fifth door on the right"],
      Saucerman2:["1. Turn right, walk down the hallway.", "2. Your destination is the sixth door on the right"],
      Saucerman1:["1. Turn right, walk down the hallway.", "2. Your destination is the seventh door on the right"],
    },
    Papin: {
      BMESmall: ["1. Walk until you make your way into hallway junction", "2. Turn right and walk down the hallway and your destination is in front of you"],
      Atrium: ["1. Walk until you make your way into hallway junction", "2. Turn right and walk down the hallway and your destination is in front of you"],
      Meyer: ["1. Destination is room to your right"],
      SharedLabSpace: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is first room on right"],
      Papin2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is second room on right"],
      Price1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is third room on right"], 
      Price2:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is fourth room on right"],
      Zunder:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is fifth room on right"],
      Barker:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is sixth room on right"],
      Peirce1:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is seventh room on right"],
      Lazzara1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the second to last room down the hall to the right"],
      Lazzara2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the last room down the hall to the right"],
      Epstein: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the last room down the hall to the left"],
      Blemker:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the second to last room down the hall to the left"],
      Jane2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the ninth room down the hall to the left"],
      Jane1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the eighth room down the hall to the left"],
      Fallahi2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the seventh room down the hall to the left"],
      Fallahi1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the sixth room down the hall to the left"],
      Saucerman2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the fifth room down the hall to the left"],
      Saucerman1:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the fourth room down the hall to the left"],
      Peirce2:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the third room down the hall to the left"],
    },
    Meyer:{
      BMESmall: ["1. Walk until you make your way into hallway junction", "2. Turn right and walk down the hallway and your destination is in front of you"],
      Atrium: ["1. Walk until you make your way into hallway junction", "2. Turn right and walk down the hallway and your destination is in front of you"],
      Meyer: ["1. Destination is room to your right"],
      SharedLabSpace: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is first room on right"],
      Papin2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is second room on right"],
      Price1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is third room on right"], 
      Price2:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is fourth room on right"],
      Zunder:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is fifth room on right"],
      Barker:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is sixth room on right"],
      Peirce1:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is seventh room on right"],
      Lazzara1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the second to last room down the hall to the right"],
      Lazzara2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the last room down the hall to the right"],
      Epstein: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the last room down the hall to the left"],
      Blemker:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the second to last room down the hall to the left"],
      Jane2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the ninth room down the hall to the left"],
      Jane1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the eighth room down the hall to the left"],
      Fallahi2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the seventh room down the hall to the left"],
      Fallahi1: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the sixth room down the hall to the left"],
      Saucerman2: ["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the fifth room down the hall to the left"],
      Saucerman1:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the fourth room down the hall to the left"],
      Peirce2:["1. Walk until you reach hallway junction", "2. Walk forward past hallway junction and your destination is the third room down the hall to the left"],  
    }
  };

  function getDirections(start, end) {
    if (start === end) return "You are already here.";

    const custom = directionMap[start]?.[end];
    if (custom) return custom.join("<br>");

    return `Mapping not required`;
  }

  // Attach click handlers to all room buttons
  roomNames.forEach((roomId) => {
    const button = document.getElementById(roomId);
    if (!button) return;

    button.addEventListener("click", () => {
      if (!startRoom) {
        startRoom = roomId;
        directions.textContent = "Now Select an End Location";
      } else {
        const endRoom = roomId;
        const steps = getDirections(startRoom, endRoom);
        directions.innerHTML = steps;

        // Strip out the HTML and join into a single string to speak
        const spokenText = steps.replace(/<br>/g, ". ");
        speakText(spokenText);

        startRoom = null; // Reset after full path
      }
    });
  });
});


